version: '2'
services:
    app:
        build: .
        command: node index.js
        # network_mode: "host"
        volumes:
            - .:/app
        ports:
            - 3000:3000
        depends_on:
            - db
    db:
        image: mongo:3.6
        # network_mode: "host"
        volumes:
           - ./data:/data/db
        ports:
            - 27017:27017
